name: flutter_xox_app
description: A new Flutter project.
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter


  shared_constants: 
    path: packages/shared_constants
  shared_widgets: 
    path: packages/shared_widgets
  cupertino_icons: ^1.0.2
  go_router: ^9.0.3
  flame: ^1.8.1
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5
  google_fonts: ^6.1.0
  flame_rive: ^1.9.4
  rive: ^0.11.16


# Developer Dependencies
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.4.6

flutter_gen:
  output: lib/app/gen/ # Optional (default: lib/gen/)
  line_length: 80 # Optional (default: 80)
  integrations:
    flutter_svg: true
    flare_flutter: true
    rive: true
    lottie: true

# Flutter Settings
flutter:
  uses-material-design: true
  generate: true
  assets:
     - assets/animations/
     - assets/images/
    